name: calculator
description: Cross Platform Calculator App.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_neumorphic: ^3.2.0
  google_fonts: ^2.1.1
  just_audio: ^0.9.18
  math_expressions: ^2.3.0
  shared_preferences: ^2.0.11
  vibration: ^1.7.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
