name: calculator
description: Cross Platform Calculator App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  google_fonts: ^2.1.1
  flutter_icons: ^1.1.0
  auto_size_text: ^3.0.0
  math_expressions: ^2.3.0
  animated_text_kit: ^4.2.1
  adaptive_theme: ^2.3.0
  vibration: ^1.7.3
  just_audio: ^0.9.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
