name: calculator
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^5.1.0
  adaptive_theme: ^3.3.0
  auto_size_text: ^3.0.0
  math_expressions: ^2.4.0
  show_up_animation: ^2.0.0
  shared_preferences: ^2.2.0
  flutter_icons_null_safety: ^1.1.0
  flutter_neumorphic:
    path: ./flutter_neumorphic

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  # flutter pub run flutter_launcher_icons:main

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "#0B0B0B"
  image: assets/splash.png
  color_dark: "#0B0B0B"
  image_dark: assets/splash.png
  android: true
  ios: false
  web: false
  android_gravity: fill_horizontal #center, fill, fill_horizontal
  fullscreen: true
