name: calculator
description: Cross Platform Calculator App.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  adaptive_theme: ^3.2.1
  auto_size_text: ^3.0.0
  flutter_icons_null_safety: ^1.1.0
  flutter_neumorphic: ^3.2.0
  google_fonts: ^4.0.4
  just_audio: ^0.9.32
  math_expressions: ^2.4.0
  shared_preferences: ^2.1.1
  vibration: ^1.7.7
  show_up_animation: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  # flutter pub run flutter_launcher_icons:main

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "#0B0B0B"
  image: assets/splash.png
  color_dark: "#0B0B0B"
  image_dark: assets/splash.png
  android: true
  ios: false
  web: false
  android_gravity: fill_horizontal #center, fill, fill_horizontal
  fullscreen: true
